services:
  database:
    image: postgres:latest
    container_name: linkhub-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
    volumes:
      - linkhub-db-data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: linkhub
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
      POSTGRES_ADDR: database
      POSTGRES_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
  nginx:
    image: nginx:alpine
    container_name: linkhub-nginx
    restart: always
    ports:
      - "8001:8001" # API Domain
      - "8002:8002" # Redirection Domain
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - backend

volumes:
  linkhub-db-data:
