services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: linkhub-swagger
    restart: always
    ports:
      - "8003:8080"
    environment:
      - SWAGGER_JSON=/docs/openapi.yml
    volumes:
      - ./docs:/docs
